using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using OMS.Models;
using OMS.Services;

namespace OMS.ViewModels;

public partial class AddClothViewModel : ObservableObject
{
    private readonly IDataService _dataService;
    private readonly Cloth? _existingCloth;
    private readonly bool _isEditMode;
    private bool _isInitializing;

    [ObservableProperty]
    private string pageTitle = "Add New Cloth";

    [ObservableProperty]
    private string submitButtonText = "Add to Inventory";
    
    [ObservableProperty]
    private string uniqueCode = string.Empty;
    
    [ObservableProperty]
    private bool isUniqueCodeVisible;

    [ObservableProperty]
    private string name = string.Empty;

    [ObservableProperty]
    private string color = string.Empty;

    [ObservableProperty]
    private string pricePerMeter = string.Empty;

    [ObservableProperty]
    private string totalMeters = string.Empty;

    [ObservableProperty]
    private string nameError = string.Empty;

    [ObservableProperty]
    private string colorError = string.Empty;

    [ObservableProperty]
    private string priceError = string.Empty;

    [ObservableProperty]
    private string metersError = string.Empty;

    [ObservableProperty]
    private bool hasPreview;

    [ObservableProperty]
    private string previewText = string.Empty;

    [ObservableProperty]
    private Color previewColor = Colors.Gray;

    [ObservableProperty]
    private string previewPrice = string.Empty;

    [ObservableProperty]
    private string previewMeters = string.Empty;

    [ObservableProperty]
    private string previewValue = string.Empty;

    // Constructor for Add mode
    public AddClothViewModel(IDataService dataService)
    {
        _dataService = dataService;
        _isEditMode = false;
        IsUniqueCodeVisible = false; // Hide for new cloths (will be auto-generated)
    }

    // Constructor for Edit mode
    public AddClothViewModel(IDataService dataService, Cloth cloth)
    {
        _dataService = dataService;
        _existingCloth = cloth;
        _isEditMode = true;
        _isInitializing = true; 

        PageTitle = "Edit Cloth";
        SubmitButtonText = "Update Cloth";
        
        UniqueCode = cloth.UniqueCode;
        IsUniqueCodeVisible = true;

        // Pre-populate fields without triggering UpdatePreview
        name = cloth.Name;
        color = cloth.Color;
        pricePerMeter = cloth.PricePerMeter.ToString();
        totalMeters = cloth.TotalMeters.ToString();
        _isInitializing = false;
    }

    [RelayCommand]
    private async Task AddCloth()
    {
        var isValid = true;

        if (string.IsNullOrWhiteSpace(Name))
        {
            NameError = "Cloth name is required";
            isValid = false;
        }

        if (string.IsNullOrWhiteSpace(Color))
        {
            ColorError = "Color is required";
            isValid = false;
        }

        if (string.IsNullOrWhiteSpace(PricePerMeter) || !double.TryParse(PricePerMeter, out var price) || price <= 0)
        {
            PriceError = "Valid price is required";
            isValid = false;
        }

        if (string.IsNullOrWhiteSpace(TotalMeters) || !double.TryParse(TotalMeters, out var meters) || meters <= 0)
        {
            MetersError = "Valid meters is required";
            isValid = false;
        }

        if (!isValid) return;

        double.TryParse(PricePerMeter, out double priceValue);
        double.TryParse(TotalMeters, out double metersValue);

        if (_isEditMode && _existingCloth != null)
        {
            // Edit mode - update existing cloth
            // UniqueCode remains the same (not editable)
            var updatedCloth = new Cloth
            {
                Id = _existingCloth.Id,
                UniqueCode = _existingCloth.UniqueCode, // Keep existing UniqueCode
                Name = Name,
                Color = Color,
                PricePerMeter = priceValue,
                TotalMeters = metersValue,
                RemainingMeters = _existingCloth.RemainingMeters + (metersValue - _existingCloth.TotalMeters),
                AddedDate = _existingCloth.AddedDate
            };

            await _dataService.UpdateClothAsync(updatedCloth);
        }
        else
        {
            // Add mode - create new cloth
            // UniqueCode will be auto-generated by the service
            var cloth = new Cloth
            {
                Name = Name,
                Color = Color,
                PricePerMeter = priceValue,
                TotalMeters = metersValue,
                RemainingMeters = metersValue,
                AddedDate = DateTime.Now,
                UniqueCode = string.Empty // Will be auto-generated
            };

            await _dataService.AddClothAsync(cloth);
        }

        await Close();
    }

    [RelayCommand]
    private async Task Close()
    {
        await Shell.Current.Navigation.PopModalAsync();
    }
}
