-- Create enums
CREATE TYPE DRESS_ORDER_STATUS AS ENUM ('Pending', 'Completed', 'Delivered');
CREATE TYPE USER_ROLE AS ENUM ('Admin', 'Maker');



-- Users table
CREATE TABLE USERS (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    ROLE USER_ROLE NOT NULL DEFAULT 'Maker',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Employees table (Makers)
CREATE TABLE EMPLOYEES (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    MOBILE_NUMBER VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Cloths table (Inventory)
CREATE TABLE CLOTHS (
    ID SERIAL PRIMARY KEY,
    UNIQUE_CODE VARCHAR(50) NOT NULL UNIQUE,
    NAME VARCHAR(255) NOT NULL,
    COLOR VARCHAR(100) NOT NULL,
    PRICE_PER_METER NUMERIC(10, 2) NOT NULL CHECK (PRICE_PER_METER >= 0),
    TOTAL_METERS NUMERIC(10, 2) NOT NULL CHECK (TOTAL_METERS >= 0),
    REMAINING_METERS NUMERIC(10, 2) NOT NULL CHECK (REMAINING_METERS >= 0),
    ADDED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT check_remaining_not_exceed_total CHECK (REMAINING_METERS <= TOTAL_METERS)
);

-- Dress Orders table
CREATE TABLE DRESS_ORDERS (
    ID SERIAL PRIMARY KEY,
    UNIQUE_CODE VARCHAR(50) NOT NULL UNIQUE,
    CUSTOMER_NAME VARCHAR(255) NOT NULL,
    MOBILE_NUMBER VARCHAR(20) NOT NULL,
    DRESS_TYPE VARCHAR(100) NOT NULL,
    CLOTH_ID INTEGER NOT NULL,
    METERS_USED NUMERIC(10, 2) NOT NULL CHECK (METERS_USED > 0),
    STATUS dress_order_status NOT NULL DEFAULT 'Pending',
    ASSIGNED_TO INTEGER NOT NULL,
    ORDER_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cloth FOREIGN KEY (CLOTH_ID) REFERENCES CLOTHS(ID) ON DELETE RESTRICT,
    CONSTRAINT fk_employee FOREIGN KEY (ASSIGNED_TO) REFERENCES EMPLOYEES(ID) ON DELETE RESTRICT
);

-- Create indexes for better query performance
CREATE INDEX idx_cloths_unique_code ON CLOTHS(UNIQUE_CODE);
CREATE INDEX idx_cloths_remaining_meters ON CLOTHS(REMAINING_METERS);
CREATE INDEX idx_dress_orders_unique_code ON DRESS_ORDERS(UNIQUE_CODE);
CREATE INDEX idx_dress_orders_status ON DRESS_ORDERS(STATUS);
CREATE INDEX idx_dress_orders_assigned_to ON DRESS_ORDERS(ASSIGNED_TO);
CREATE INDEX idx_dress_orders_cloth_id ON DRESS_ORDERS(CLOTH_ID);
CREATE INDEX idx_dress_orders_order_date ON DRESS_ORDERS(ORDER_DATE);
CREATE INDEX idx_employees_username ON EMPLOYEES(USERNAME);

-- Create function to update UPDATED_AT timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.UPDATED_AT = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create triggers to auto-update updated_at
CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON USERS
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_employees_updated_at BEFORE UPDATE ON EMPLOYEES
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_cloths_updated_at BEFORE UPDATE ON CLOTHS
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_dress_orders_updated_at BEFORE UPDATE ON DRESS_ORDERS
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Insert sample data (optional)
-- Insert default admin user
INSERT INTO USERS (NAME, ROLE) VALUES ('Admin User', 'Admin');

-- Insert sample employees
INSERT INTO EMPLOYEES (NAME, USERNAME, PASSWORD, MOBILE_NUMBER) 
VALUES 
    ('John Doe', 'john.doe', 'password123', '+1234567890'),
    ('Jane Smith', 'jane.smith', 'password123', '+1234567891');

-- Insert sample cloths
INSERT INTO CLOTHS (UNIQUE_CODE, NAME, COLOR, PRICE_PER_METER, TOTAL_METERS, REMAINING_METERS, ADDED_DATE)
VALUES
    ('CLT001', 'Cotton Fabric', 'Blue', 15.50, 100.00, 100.00, CURRENT_TIMESTAMP),
    ('CLT002', 'Silk Fabric', 'Red', 35.00, 50.00, 50.00, CURRENT_TIMESTAMP),
    ('CLT003', 'Linen Fabric', 'White', 25.00, 75.00, 75.00, CURRENT_TIMESTAMP);

-- Grant permissions (adjust as needed for your database user)
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO your_db_user;
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO your_db_user;

COMMENT ON TABLE USERS IS 'System users with roles (Admin/Maker)';
COMMENT ON TABLE EMPLOYEES IS 'Employee/Maker details with login credentials';
COMMENT ON TABLE CLOTHS IS 'Cloth inventory with pricing and availability';
COMMENT ON TABLE DRESS_ORDERS IS 'Customer dress orders with status tracking';
